/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#3f0032",
        "on-primary": "#000c9f",
        "on-surface": "#ffffff",
        "secondary-container": "#45359e",
        "primary-dim": "#5764f1",
        "error-container": "#a70138",
        "on-tertiary": "#71175b",
        "primary-container": "#8e98ff",
        "on-background": "#ffffff",
        "outline-variant": "#484849",
        "on-secondary": "#1d0071",
        "secondary-fixed": "#d3ccff",
        "on-secondary-fixed-variant": "#4f40a9",
        "surface-container-low": "#131314",
        "surface-container-lowest": "#000000",
        "secondary-dim": "#9d8ffd",
        "inverse-surface": "#fcf8f9",
        "inverse-primary": "#404dda",
        "tertiary": "#ffa9df",
        "secondary-fixed-dim": "#c5bcff",
        "on-primary-fixed-variant": "#000b98",
        "surface": "#0e0e0f",
        "tertiary-dim": "#f084cc",
        "on-surface-variant": "#adaaab",
        "primary-fixed-dim": "#7d88ff",
        "error-dim": "#d73357",
        "primary-fixed": "#8e98ff",
        "primary": "#9fa7ff",
        "tertiary-fixed": "#ff91da",
        "inverse-on-surface": "#565556",
        "surface-tint": "#9fa7ff",
        "tertiary-container": "#ff91da",
        "on-tertiary-container": "#640951",
        "on-error": "#490013",
        "tertiary-fixed-dim": "#f084cc",
        "surface-container": "#1a191b",
        "on-secondary-fixed": "#321e8b",
        "surface-container-highest": "#262627",
        "on-error-container": "#ffb2b9",
        "error": "#ff6e84",
        "on-primary-container": "#00087d",
        "secondary": "#9d8ffd",
        "on-primary-fixed": "#000000",
        "surface-variant": "#262627",
        "surface-container-high": "#201f21",
        "surface-bright": "#2c2c2d",
        "on-secondary-container": "#d2caff",
        "outline": "#767576",
        "background": "#0e0e0f",
        "on-tertiary-fixed-variant": "#6f165a",
        "surface-dim": "#0e0e0f"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
    },
  },
  plugins: [],
}